# Generated by Django 6.0.1 on 2026-03-04 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('transaction_type', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('is_fraud', models.BooleanField(default=False)),
            ],
        ),
    ]
